platform :ios, '10.0'

target 'GithubBrowser' do
  use_frameworks!

  pod 'Siesta/UI', path: '../..'
end

target "GithubBrowserCombine" do
	use_frameworks!
	platform :ios, '13.0'
	pod 'Siesta/UI', path: '../..'
	pod 'CombineCocoa'
	pod 'CombineExt'
	pod 'CombineDataSources'
end

target "GithubBrowserRx" do
	use_frameworks!
	pod 'Siesta/UI', path: '../..'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'RxOptional'
end
